### ISSUE TITLE
Didn't work for me

### ISSUE THREAD

**Issue by gpassero** [linw1995/python-traceback-jumper#1]
I installed and activated the extension, but it didn't work. When I try to click the files path in Terminal output, only a part of it gets a underline (up to the first whitespace).

**Comment by linw1995** [comment]
Can you take a screenshot?tell me how to reappear the error.

**Comment by gpassero** [comment]
After I disabled the extension the first part of the path keeps getting underlined, so I don't think its a matter with your extension. 

I installed the extension again and ran a script via prompt (F7) and task (ctrl+shift+b) and I can't get the jumper to work.

Task runer:

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "python",
    "isShellCommand": true,
    "args": ["${file}"],
    "showOutput": "always"
}
```


Example code:

```python
            if None is is nt None:
                break
```

Output:

![image](https://cloud.githubusercontent.com/assets/4478523/24584000/050fa968-1734-11e7-8417-b26f455d9adb.png)

I tried to click on the path and on the line, but nothing happens.

**Comment by linw1995** [comment]
maybe other extensions and mine conflict?you disable other extensions, and try it again.

**Comment by gpassero** [comment]
@linw1995  I disabled all extensions (Python, MagicPython, Git Log) and it still doesn't work. :(

**Comment by linw1995** [comment]
@gpassero i fix it, you can update extension and try it agian.
thank you :), have a nice day.
